runtime: go122

service_account: go-cicd@root-territory-454510-c5.iam.gserviceaccount.com

env_variables:
  PORT: "8080"


# Health check configuration
# liveness_check:
#   path: "/"
#   check_interval_sec: 30
#   timeout_sec: 4
#   failure_threshold: 2
#   success_threshold: 1

# readiness_check:
#   path: "/"
#   check_interval_sec: 5
#   timeout_sec: 4
#   failure_threshold: 2
#   success_threshold: 1
#   app_start_timeout_sec: 300


